# theme: gruvbox-high-dark
background              #282828
foreground              #EBDBB2
cursor                  #EBDBB2
cursor_text_color       #282828
selection_foreground    #EBDBB2
selection_background    #665C54
active_tab_background   #504945
active_tab_foreground   #D79921
inactive_tab_background #3C3836
inactive_tab_foreground #928374

background_opacity 0.90
