background = 0xFF282828
base = 0xFF504945
text = 0xFFEBDBB2
alternate_base = 0xFF3C3836
bright_text = 0xFFD4BE98
accent = 0xFFD4BE98
link_text = 0xFFD4BE98
accent_secondary = 0xFFFABD2F
font_family = "IBM Plex Mono"
font_family_monospace = "monospace"
font_size = 13
small_font_size = 10
rounding_large = 8
rounding_small = 4
